// Writes crates/leafcutter-ant/src/json/json5_unicode.rs: the character
// classes json5 2.2.1 uses for whitespace and unquoted property names. json5
// ships its own Unicode 10 tables, which differ from the Unicode version any
// Rust crate carries, so the tables are copied out of json5 itself by asking
// its predicates about every code point.
//
// Usage: npm ci && npm run vectors   (from tools/parity)

import { writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import { fileURLToPath } from "node:url"

const require = createRequire(import.meta.url)
const util = require("json5/lib/util.js")
const { version } = require("json5/package.json")
const out = fileURLToPath(new URL("../../crates/leafcutter-ant/src/json/json5_unicode.rs", import.meta.url))

function ranges(predicate) {
	const result = []
	let start = -1
	for (let cp = 0; cp <= 0x110000; cp++) {
		// Surrogates cannot occur in a Rust char, so they are never asked about.
		const inside = cp < 0x110000 && !(cp >= 0xd800 && cp <= 0xdfff) && predicate(String.fromCodePoint(cp))
		if (inside && start < 0) start = cp
		if (!inside && start >= 0) {
			result.push([start, cp - 1])
			start = -1
		}
	}
	return result
}

const hex = (n) => "0x" + n.toString(16).toUpperCase().padStart(4, "0")
function table(name, doc, predicate) {
	const rows = ranges(predicate).map(([a, b]) => `\t(${hex(a)}, ${hex(b)}),`)
	return `/// ${doc}\n#[rustfmt::skip]\npub(super) const ${name}: &[(u32, u32)] = &[\n${rows.join("\n")}\n];\n`
}

writeFileSync(
	out,
	[
		`// Generated by tools/parity/unicode-tables.mjs from json5 ${version}. Do not edit;`,
		"// run `npm run vectors` in tools/parity instead.",
		"",
		table("SPACE_SEPARATOR", "`util.isSpaceSeparator`: the extra whitespace json5 skips between tokens.", util.isSpaceSeparator),
		table("ID_START", "`util.isIdStartChar`: characters that may start an unquoted property name.", util.isIdStartChar),
		table("ID_CONTINUE", "`util.isIdContinueChar`: characters that may continue an unquoted property name.", util.isIdContinueChar),
	].join("\n"),
)
